# Generated by Django 4.2.10 on 2026-02-24 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_deliveryinfo_paymentinfo_termsinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Заголовок')),
                ('subtitle', models.CharField(blank=True, max_length=200, verbose_name='Подзаголовок')),
                ('content', models.TextField(blank=True, verbose_name='Текст')),
                ('image', models.ImageField(blank=True, null=True, upload_to='blocks/', verbose_name='Изображение')),
                ('image_alt', models.CharField(blank=True, max_length=200, verbose_name='Альт. текст')),
                ('block_type', models.CharField(choices=[('hero', 'Главный экран'), ('about', 'О компании'), ('advantages', 'Преимущества'), ('quote', 'Цитата'), ('text', 'Текст с изображением'), ('custom', 'Произвольный')], default='custom', max_length=20, verbose_name='Тип блока')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Контентный блок',
                'verbose_name_plural': 'Контентные блоки',
                'ordering': ['order'],
            },
        ),
    ]
