# Generated by Django 4.2.10 on 2026-03-03 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_contentblock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentblock',
            name='block_type',
            field=models.CharField(choices=[('hero', 'Главный экран'), ('services', 'Услуги'), ('terms', 'Сроки'), ('payment', 'Оплата'), ('delivery', 'Доставка'), ('portfolio', 'Портфолио'), ('contact', 'Контакты'), ('about', 'О компании'), ('advantages', 'Преимущества'), ('quote', 'Цитата'), ('text', 'Текст с изображением'), ('custom', 'Произвольный')], default='custom', max_length=20, verbose_name='Тип блока'),
        ),
    ]
