# Generated by Django 4.2.10 on 2026-03-16 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_contentblock_block_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Уникальный код, например: hero, terms, payment, delivery, contact', unique=True, verbose_name='Код секции')),
                ('section_type', models.CharField(choices=[('hero', 'Главный экран'), ('services', 'Услуги'), ('cards', 'Карточки'), ('gallery', 'Галерея'), ('delivery', 'Доставка'), ('contact', 'Контакты'), ('text', 'Текстовый блок'), ('custom', 'Произвольный блок')], default='text', max_length=20, verbose_name='Тип секции')),
                ('menu_title', models.CharField(blank=True, max_length=100, verbose_name='Название в меню')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Заголовок')),
                ('subtitle', models.CharField(blank=True, max_length=255, verbose_name='Подзаголовок')),
                ('content', models.TextField(blank=True, verbose_name='Текст')),
                ('image', models.ImageField(blank=True, null=True, upload_to='sections/', verbose_name='Изображение')),
                ('image_alt', models.CharField(blank=True, max_length=200, verbose_name='Alt текст изображения')),
                ('button_text', models.CharField(blank=True, max_length=100, verbose_name='Текст кнопки')),
                ('button_url', models.CharField(blank=True, max_length=255, verbose_name='Ссылка кнопки')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('show_in_menu', models.BooleanField(default=True, verbose_name='Показывать в меню')),
            ],
            options={
                'verbose_name': 'Секция главной страницы',
                'verbose_name_plural': 'Секции главной страницы',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HomeSectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('card', 'Карточка'), ('text', 'Текст'), ('image', 'Изображение'), ('action', 'Кнопка / ссылка')], default='card', max_length=20, verbose_name='Тип элемента')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Заголовок')),
                ('subtitle', models.CharField(blank=True, max_length=255, verbose_name='Подзаголовок')),
                ('content', models.TextField(blank=True, verbose_name='Текст')),
                ('image', models.ImageField(blank=True, null=True, upload_to='section_items/', verbose_name='Изображение')),
                ('image_alt', models.CharField(blank=True, max_length=200, verbose_name='Alt текст изображения')),
                ('price', models.CharField(blank=True, max_length=100, verbose_name='Цена / подпись')),
                ('link_text', models.CharField(blank=True, max_length=100, verbose_name='Текст ссылки')),
                ('link_url', models.CharField(blank=True, max_length=255, verbose_name='Ссылка')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='main.homesection', verbose_name='Секция')),
            ],
            options={
                'verbose_name': 'Элемент секции',
                'verbose_name_plural': 'Элементы секций',
                'ordering': ['order'],
            },
        ),
    ]
