# Generated by Django 4.2.10 on 2026-03-19 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_homesection_homesectionitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(blank=True, max_length=200, verbose_name='Название сайта')),
                ('hero_badge', models.CharField(blank=True, default='Печать для бизнеса и частных клиентов', max_length=255, verbose_name='Текст бейджа в hero')),
                ('hero_primary_button', models.CharField(blank=True, default='Рассчитать стоимость', max_length=100, verbose_name='Текст главной кнопки')),
                ('hero_secondary_button', models.CharField(blank=True, default='Смотреть продукцию', max_length=100, verbose_name='Текст второй кнопки')),
                ('contact_form_title', models.CharField(blank=True, default='ОТПРАВЬТЕ ФОРМУ ИЛИ СВЯЖИТЕСЬ С НАМИ САМОСТОЯТЕЛЬНО', max_length=255, verbose_name='Заголовок формы')),
                ('consent_text', models.CharField(blank=True, default='Я соглашаюсь с правилами обработки данных', max_length=255, verbose_name='Текст согласия')),
                ('submit_button_text', models.CharField(blank=True, default='ОТПРАВИТЬ', max_length=100, verbose_name='Текст кнопки отправки')),
                ('telegram_url', models.URLField(blank=True, verbose_name='Ссылка на Telegram')),
                ('telegram_button_text', models.CharField(blank=True, default='TELEGRAM', max_length=50, verbose_name='Текст кнопки Telegram')),
                ('whatsapp_url', models.URLField(blank=True, verbose_name='Ссылка на WhatsApp')),
                ('whatsapp_button_text', models.CharField(blank=True, default='WHATSAPP', max_length=50, verbose_name='Текст кнопки WhatsApp')),
            ],
            options={
                'verbose_name': 'Настройки сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
    ]
