# Generated by Django 4.2.10 on 2026-03-19 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='footer_text',
            field=models.CharField(blank=True, default='© 2026 Типография. Все права защищены.', max_length=255, verbose_name='Текст в подвале'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='modal_submit_button_text',
            field=models.CharField(blank=True, default='Отправить', max_length=100, verbose_name='Текст кнопки модального окна'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='modal_title',
            field=models.CharField(blank=True, default='Рассчитать стоимость', max_length=200, verbose_name='Заголовок модального окна'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_name',
            field=models.CharField(blank=True, default='Типография', max_length=200, verbose_name='Название сайта'),
        ),
    ]
