# Generated by Django 4.2.10 on 2026-03-24 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_sitesettings_footer_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='contact_menu_title',
            field=models.CharField(blank=True, default='Контакты', max_length=100, verbose_name='Название "Контакты" в меню'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_section_title',
            field=models.CharField(blank=True, default='КОНТАКТЫ', max_length=200, verbose_name='Заголовок раздела "Контакты"'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='delivery_menu_title',
            field=models.CharField(blank=True, default='Доставка', max_length=100, verbose_name='Название "Доставка" в меню'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='delivery_section_title',
            field=models.CharField(blank=True, default='ДВА ВАРИАНТА ДОСТАВКИ', max_length=200, verbose_name='Заголовок раздела "Доставка"'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='payment_menu_title',
            field=models.CharField(blank=True, default='Оплата', max_length=100, verbose_name='Название "Оплата" в меню'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='payment_section_title',
            field=models.CharField(blank=True, default='ОПЛАТА', max_length=200, verbose_name='Заголовок раздела "Оплата"'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='portfolio_menu_title',
            field=models.CharField(blank=True, default='Оборудование', max_length=100, verbose_name='Название "Портфолио" в меню'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='portfolio_section_subtitle',
            field=models.CharField(blank=True, default='Наше оборудование и производственные возможности', max_length=255, verbose_name='Подзаголовок раздела "Портфолио"'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='portfolio_section_title',
            field=models.CharField(blank=True, default='ОБОРУДОВАНИЕ', max_length=200, verbose_name='Заголовок раздела "Портфолио"'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='services_menu_title',
            field=models.CharField(blank=True, default='Услуги', max_length=100, verbose_name='Название "Услуги" в меню'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='services_section_title',
            field=models.CharField(blank=True, default='НАША ПРОДУКЦИЯ', max_length=200, verbose_name='Заголовок раздела "Услуги"'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='terms_menu_title',
            field=models.CharField(blank=True, default='Сроки', max_length=100, verbose_name='Название "Сроки" в меню'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='terms_section_title',
            field=models.CharField(blank=True, default='СРОКИ', max_length=200, verbose_name='Заголовок раздела "Сроки"'),
        ),
    ]
