# Generated by Django 4.2.10 on 2026-03-24 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_sitesettings_contact_menu_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='portfolio_section_text',
            field=models.TextField(blank=True, default='Многие клиенты не знают, что большая часть полиграфических компаний является посредниками. Они имеют множество центров приема заказов, но сами не могут отвечать за качество и сроки. А их клиенты каждый раз переплачивают посредническую комиссию.\n\nПри этом наличие на сайте фото оборудования ничего не значит. Хотите отличить посредника от реальной типографии, просто спросите у менеджера: «А можно приехать на ваше производство и увидеть, как печатается продукция..?»', verbose_name='Текст блока оборудования'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='portfolio_section_title',
            field=models.CharField(default='СОБСТВЕННОЕ ПРОИЗВОДСТВО', max_length=255, verbose_name='Заголовок блока оборудования'),
        ),
    ]
