# Generated by Django 4.2.10 on 2026-03-31 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_sitesettings_portfolio_section_subtitle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='pickup_route_button_text',
            field=models.CharField(blank=True, default='Куда идти — схема прохода', max_length=100, verbose_name='Текст кнопки схемы прохода'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='pickup_route_url',
            field=models.URLField(blank=True, default='', verbose_name='Ссылка на схему прохода'),
        ),
    ]
